language: csharp
mono: none
dist: trusty
dotnet: "2.1.500"
solution: Stashy.sln

sudo: required
services:
  - docker

install: 
  - "dotnet restore"
script: 
  - "dotnet build"

env:
  global:
    - secure: "qOWWvPwemZH7BV0fGnK5X9MT2A8z4A4Jh07SrTkOJJHE2EektuJ8tmok75bGyvyEYLHmAl2BG8i13aDFUQQzX/aJF9ilbz+gopHnTXHQFJTp7c+TAcO5oIXj9MjItjRwz1Wmgy+yaFmiq2TP27Yg0INGQy+RtiHMz5SjSqA+nH4wsxpzuWQJNDGjMuQZU9SohzMy92uWVyQNOOpiR5/W+3o5BNMSQgRInKIQtZK6vozKAxARag+JnfdYh7ANtWnUYTBKwA3Ia7g5NgAbSRJRXmF92fOFmUQqB89soPzdk5nraS2UORiqJG3gVmR1UhErGuU+o1v9tX++yGrMVirGUhMlSPDkhp+I2fRAn5PTULVRTj6cj50nHTwjvpK+NgjiWlvZP5U7WxvzcCOS77RBVDxmlaG6HttPpTwZGnqKLvxVw08lNLGxjcza2Z0J7pjBVTr3GWKozUei2rfJcfGS+g9yVnVET8FnJ82D67W5SkkFuo2gt9Uqt6fZpVHLvhDOa+P1F/6xaZPLiDXCO48OE/ymVb3tLhKFU1FO14I6JlZjXJl1OnGnqtYU2Bcr1PlVAqkeClcnYk1rVz1EKbWmCOVkIC/152EFFeC7RFWp4wXDIU8FCj9TLBpBYpyX5m3jD9XXuXCorW+1kY/gTwtNHWhykb8ITFPnYuVfxjsmoVk=" # DOCKER_USERNAME
    - secure: "EXx9o4GceiNQKBe5NpeyVDMf6FlNJG/yVgV8GsdEKYc1iVfCFFfiClANltMC3gEHbMjAdIVgcZSN9XV1J8iNooqj0kGwsDpXUuFqrC76fQVscAxwtreCusAKNV5LjcvHF69Hp1sLIRNUH2yS8xupWkYN9Eq8fTPdm8XqYIE/r6L7S3kCi5HU4kNhl5NbkqMU9JXURfTSEJt51oyhb5gXhAjkylqpnPGQfuwNP+herTDi87Nt1h1vTY3yuBEO36vmyBJBfkIeKjbJPmPXRUq0nQSeICFLxrDAEZvxvJ+SKh8wV00IZeetYXNaGLns8kBElkCpnZlsIp8bFyPUHVG4cFEMw0DBM+ZLtFO1RxGWSFs6yt5wdf3I/QoNJkoip5PrRJfqq25cnFR/xreGKV7t9L7Jtrz4aRgd7E21R/N5ZWC0I6b7zHc2hmhCp1LlVYundn+TQAhVbcRrDT3ADi0YbC+8HnWwIFJIE5QV0Ao4M97CjInNzKNhIt6prPbhimBFxKrjQpW0Q8HoAM+Zfv6rUqDTngb4QzoU7bSC2r59YGgKiBm5zy6FDX5Lbe5k87xPCveYfJ5MS1p8sDRysDALoDMGD9qTYf3strp/dCX3dK07O0exG500Ajg7dwjtlqiI3mzZT4JkASZ93ixAGGhwspDyrhLukw9BIxmK0VxM8TE=" # DOCKER_PASSWORD
    - COMMIT=${TRAVIS_COMMIT::8}

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - export REPO=nodestry/stashy
  - export TAG=`if [ "$BRANCH" == "master" ]; then echo "latest"; else echo $BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO